import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from './ReactQueryProvider';
import Link from 'next/link';
import MSW from './MswProviders';
import 'react-calendar/dist/Calendar.css';
import 'react-responsive-carousel/lib/styles/carousel.min.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <MSW>
            <nav>
              <Link href={'/matchingList'}>매칭 리스트</Link>
              <Link href={'/createMatching'}>매칭작성</Link>
              <Link href={'/signUp'}>회원가입</Link>
            </nav>
            {children}
          </MSW>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
