import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from './ReactQueryProvider';
import Link from 'next/link';
import 'react-calendar/dist/Calendar.css';
import 'react-responsive-carousel/lib/styles/carousel.min.css';

import SessionProvider from './SessionProviders';
import NavContainer from '@/components/nav/NavContainer';
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <nav>
            <Link href={'/matchingList'}>매칭 리스트</Link>
            <Link href={'/createMatching'}>매칭작성</Link>
            <Link href={'/signUp'}>회원가입</Link>
            <Link href={'/signIn'}>로그인</Link>
          </nav>
          <SessionProvider session={session}>
            <NavContainer></NavContainer>
          </SessionProvider>

          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
