import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ReactQueryProvider from './ReactQueryProvider';
import Link from 'next/link';
import 'react-calendar/dist/Calendar.css';
import 'react-responsive-carousel/lib/styles/carousel.min.css';

import SessionProvider from './SessionProviders';
import NavContainer from '@/components/nav/NavContainer';
import { getServerSession } from 'next-auth';
import Footer from '@/components/footer/Footer';
import { authOptions } from './api/auth/[...nextauth]/route';

const myFont = localFont({
  src: './Jalnan2TTF.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={myFont.className}>
          <ReactQueryProvider>
            <NavContainer></NavContainer>

            {children}
            <Footer></Footer>
          </ReactQueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
